# Generated by Django 2.1 on 2018-09-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='sno',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
