# Generated by Django 2.1 on 2018-09-16 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_exercise_sno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='id',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sno',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
